name: homelab

include:
  - apps/jellyfin/docker-compose.yml
  - apps/stremio/docker-compose.yml
  - apps/blocky/docker-compose.yml
  - apps/monitoring/docker-compose.yml
  - apps/proxy/docker-compose.yml
